use_frameworks!
platform :ios, '8.3'

target 'SwiftKickiOSDemo' do
  # Use the latest and greatest, pre-release versions 
  pod 'SwiftKick', :path => '../../SwiftKick-Local.podspec'
end

# -------------------------------------------------

# target 'SwiftKickTests' do
# end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.3'
        end
    end
end
